FROM python:3.8-alpine

WORKDIR /tzedaka/tzedaka-app/server

# Copia el archivo requirements.txt y luego instala las dependencias
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copia el resto de los archivos de la aplicación al contenedor
COPY . .

# Cambia la propiedad de los archivos y directorios al usuario no root
RUN chown -R nobody:nogroup /tzedaka/tzedaka-app/server

# Cambia al usuario no root
USER nobody

# Copia el script de inicio y configura permisos de ejecución
COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

# Define el comando para ejecutar la aplicación a través del script de inicio
CMD ["./start_app.sh"]
